/* AUTO-GENERATED by build_search_index.py — do not edit the part above
 * the MANUAL-ENTRIES markers; it is overwritten on every run.
 *
 *   rebuild once        python build_search_index.py
 *   rebuild on change   python build_search_index.py --watch
 *
 * Last changed: 2026-09-26 21:52 from 4 page(s).
 *
 * To add a result that is not a page in this repo (an external link, for
 * instance), put it between the two MANUAL-ENTRIES markers below.
 */

window.SITE_SEARCH_INDEX = [
    // ---- generated from the *.html files ----
    {
        title: "Home",
        url: "index.html",
        text: "Home I am a PhD student in Economics at UT Austin working on behavioral economics, macro-finance, causal inference, and machine learning. Tianyu, Yan, PhD, University of Texas, Austin, Research, Teaching, Blog Home I am a PhD student in Economics at the University of Texas, Austin. Before joining UT Austin, I received my B.A. in Computer Science and Economics from New York University. RESEARCH INTERESTS Behavioral Economics CV Click here for a copy of my CV. CONTACT Email: tianyu.yan@utexas.edu"
    },
    {
        title: "Blogs — Recent Posts",
        url: "blog.html",
        text: "Blogs — Recent Posts Occasional writing by Albert Tianyu Yan on research, innovation and academic life, alongside notes on papers and teaching in economics. Blog, Research, Innovation, Academic Life Blogs This is where I occasionally post thoughts on research, opinions, and academic life. Recent Posts"
    },
    {
        title: "Research",
        url: "research.html",
        text: "Research Working papers and research in progress by Albert Tianyu Yan, PhD student in Economics at the University of Texas at Austin. Slides and paper links. PhD, University of Texas, Austin, Research, Working Papers, Publications, Projects Research Working Papers From Idea to Innovation: Scientific Disclosures, Technology News, and Business Cycles [slides] Selected Work in Progress"
    },
    {
        title: "Teaching — Teaching Assistant",
        url: "teaching.html",
        text: "Teaching — Teaching Assistant Courses taught by Albert Tianyu Yan as a teaching assistant at the University of Texas at Austin: econometrics, machine learning and causal inference. Teaching, PhD, University of Texas, Austin Teaching Teaching Assistant University of Texas at Austin Causal Inference Python, Databases, and Big Data Machine Learning Econometrics Financial Literacy Financial Economics Mathematical Microeconomics Theory Macroeconomics Theory"
    },

    // ---- hand-written entries, preserved as-is ----
    /* MANUAL-ENTRIES-START */
    {
        title: "CV (PDF on Google Drive)",
        url: "https://drive.google.com/file/d/10ALan3dw9dSdMoITfeqEgj5Hn8NKNeBR/view?usp=sharing",
        text: "cv curriculum vitae resume vita download pdf"
    },
    /* MANUAL-ENTRIES-END */
];
