/* AUTO-GENERATED by build_search_index.py — do not edit the part above
 * the MANUAL-ENTRIES markers; it is overwritten on every run.
 *
 *   rebuild once        python build_search_index.py
 *   rebuild on change   python build_search_index.py --watch
 *
 * Last changed: 2026-09-26 21:52 from 4 page(s).
 *
 * To add a result that is not a page in this repo (an external link, for
 * instance), put it between the two MANUAL-ENTRIES markers below.
 */

window.SITE_SEARCH_INDEX = [
    // ---- generated from the *.html files ----
    {
        title: "首页",
        url: "index.html",
        text: "首页 我是德克萨斯大学奥斯汀分校经济学博士生，主要研究行为经济学、宏观金融、因果推断与机器学习。 金融学, 博士, 德克萨斯大学奥斯汀分校, 研究, 教学, 博客 首页 我是德克萨斯大学奥斯汀分校经济学博士生。加入 UT Austin 之前，我在纽约大学获得计算机科学与经济学学士学位。 研究兴趣 行为经济学 简历 点击此处 查看我的简历。 联系方式 邮箱：tianyu.yan@utexas.edu"
    },
    {
        title: "博客 — 近期文章",
        url: "blog.html",
        text: "博客 — 近期文章 闫天雨的博客，不定期发布关于经济学研究、学术观点与学术生活的思考，以及论文阅读、科研方法与教学相关的笔记。 博客, 研究, 学术生活 博客 这里会不定期发布一些关于研究、观点与学术生活的思考。 近期文章"
    },
    {
        title: "研究",
        url: "research.html",
        text: "研究 闫天雨的研究，包括工作论文与在研项目。他在德克萨斯大学奥斯汀分校攻读经济学博士，研究方向涉及经济学与金融学，站内提供论文与幻灯片链接。 研究, 工作论文, 在研项目, 德克萨斯大学奥斯汀分校 研究 工作论文 From Idea to Innovation: Scientific Disclosures, Technology News, and Business Cycles [幻灯片] 在研项目"
    },
    {
        title: "教学 — 助教",
        url: "teaching.html",
        text: "教学 — 助教 闫天雨在德克萨斯大学奥斯汀分校担任助教，负责的课程包括因果推断、计量经济学、机器学习、金融经济学、数理微观经济学与宏观经济学理论等。 教学, 助教, 计量经济学, 德克萨斯大学奥斯汀分校 教学 助教 德克萨斯大学奥斯汀分校 因果推断 Python、数据库与大数据 机器学习 计量经济学 金融素养 金融经济学 数理微观经济学 宏观经济学理论"
    },

    // ---- hand-written entries, preserved as-is ----
    /* MANUAL-ENTRIES-START */
    {
        title: "简历（Google Drive 上的 PDF）",
        url: "https://drive.google.com/file/d/10ALan3dw9dSdMoITfeqEgj5Hn8NKNeBR/view?usp=sharing",
        text: "cv 简历 履历 curriculum vitae resume vita download pdf"
    },
    /* MANUAL-ENTRIES-END */
];
