/* AUTO-GENERATED by build_search_index.py — do not edit the part above
 * the MANUAL-ENTRIES markers; it is overwritten on every run.
 *
 *   rebuild once        python build_search_index.py
 *   rebuild on change   python build_search_index.py --watch
 *
 * Last changed: 2026-09-26 21:52 from 4 page(s).
 *
 * To add a result that is not a page in this repo (an external link, for
 * instance), put it between the two MANUAL-ENTRIES markers below.
 */

window.SITE_SEARCH_INDEX = [
    // ---- generated from the *.html files ----
    {
        title: "首頁",
        url: "index.html",
        text: "首頁 我是德州大學奧斯汀分校經濟學博士生，主要研究行為經濟學、宏觀金融、因果推論與機器學習。 金融學, 博士, 德州大學奧斯汀分校, 研究, 教學, 網誌 首頁 我是德州大學奧斯汀分校經濟學博士生。加入 UT Austin 之前，我在紐約大學取得計算機科學與經濟學學士學位。 研究興趣 行為經濟學 履歷 點擊此處 查看我的履歷。 聯絡方式 電郵：tianyu.yan@utexas.edu"
    },
    {
        title: "網誌 — 近期文章",
        url: "blog.html",
        text: "網誌 — 近期文章 閆天雨的網誌，不定期發佈關於經濟學研究、學術觀點與學術生活的想法，以及論文閱讀、科研方法與教學相關的筆記。 網誌, 研究, 學術生活 網誌 這裏會不定期發佈一些關於研究、觀點與學術生活的想法。 近期文章"
    },
    {
        title: "研究",
        url: "research.html",
        text: "研究 閆天雨的研究，包括工作論文與進行中的研究。他在德州大學奧斯汀分校攻讀經濟學博士，研究方向涉及經濟學與金融學，站內提供論文與投影片連結。 研究, 工作論文, 進行中的研究, 德州大學奧斯汀分校 研究 工作論文 From Idea to Innovation: Scientific Disclosures, Technology News, and Business Cycles [投影片] 進行中的研究"
    },
    {
        title: "教學 — 助教",
        url: "teaching.html",
        text: "教學 — 助教 閆天雨在德州大學奧斯汀分校擔任助教，負責的科目包括因果推論、計量經濟學、機器學習、金融經濟學、數理微觀經濟學與宏觀經濟學理論等。 教學, 助教, 計量經濟學, 德州大學奧斯汀分校 教學 助教 德州大學奧斯汀分校 因果推論 Python、數據庫與大數據 機器學習 計量經濟學 金融素養 金融經濟學 數理微觀經濟學 宏觀經濟學理論"
    },

    // ---- hand-written entries, preserved as-is ----
    /* MANUAL-ENTRIES-START */
    {
        title: "履歷（Google Drive 上的 PDF）",
        url: "https://drive.google.com/file/d/10ALan3dw9dSdMoITfeqEgj5Hn8NKNeBR/view?usp=sharing",
        text: "cv 履歷 簡歷 curriculum vitae resume vita download pdf"
    },
    /* MANUAL-ENTRIES-END */
];
